spring:
  application:
    name: excelllent-jobs
  liquibase:
    change-log: classpath:db/changelog/000.changelog-master.yaml
  datasource:
    url: jdbc:postgresql://localhost:54329/ej
    username: ej
    password: ej
  jpa:
    hibernate:
      ddl-auto: none

springdoc:
  swagger-ui:
    path: /swagger-ui.html

ferhad:
  app:
    jwtSecret: gSjOhVwYHmb5rOhn10Cqus5MK8BNUr6QJhWH9TL2RuFmsdi51dOXF6BEQx39jGB
    jwtExpirationMs: 86400000